### ISSUE TITLE
right 2 buttons don't work

### ISSUE THREAD

**Issue by ktownsend-personal** [finity69x2/cover-position-preset-row#1]
Thanks for putting this together so quickly!

I tried it out, but I can't seem to get the right 2 buttons to work. The left 2 are fine. I tried both with and without custom setpoints. I assume just a typo or something in the new code. I'm not getting any javascript errors in the browser, so no clues there.

**Comment by finity69x2** [comment]
Just to clarify, the ones that don't work are the 0% and 33% buttons?

**Comment by finity69x2** [comment]
yes, it was a typo (stupid extra 'd'). :(

I went back and forth a couple of times deciding if the "close" and "midclose" setpoints should be called that or "closed" and "midclosed". I settled on "close"/"midclose" for setpoints and "closed"/midclosed" for states. And I forgot to change the service call for those buttons.

I've updated the code so try it now.

**Comment by ktownsend-personal** [comment]
No change as far as I can tell. Still broken. Cleared browser cache to be sure.

**Comment by finity69x2** [comment]
I believe I see the issue. Actually there were two.

I still had an extra 'd' in the code where it wasn't supposed to be. Try loading the code again and try with the default setpoints.

Then if that works...

I also have the options in the repo incorrect (still based on that stupid 'd').

You'll need to change the custom setpoints for the "MidClosedPosition" and the "ClosedPosition" to "MidClosePosition" and "ClosePosition" (minus the extra 'd').

Sorry about the confusion. I don't actually have a positionable cover so I couldn't fully test that part of it.

**Comment by ktownsend-personal** [comment]
We're closer :)

Button 4 is working now.
Button 3 is giving an error: ` required key not provided @ data['position']`, both with and without custom setpoints. 

I had noticed the options grid had the "d" and your yaml example didn't, but I forgot to mention it. 

Question: does the position need to exactly match for the button to be highlighted, or is it deducing a range from the adjacent buttons?

**Comment by ktownsend-personal** [comment]
I just noticed another glitch: `customSetpoints: false` is still using my custom setpoints.

**Comment by finity69x2** [comment]
<s>which one is button 3? midClose?</s>

edit: I found my typo. try it again.

<s>I'm not sure about the custom setpoints thing. I'll have to dig in deeper on that.</s>

<s>what happens if you don't provide any "custom setpoint" information (just delete all references to custom setpoints in the config)?</s>

edit again: I think I found the setpoint thing too.

the buttons should change colors on a range based on the setpoints. the transition is half way between the setpoints.

**Comment by ktownsend-personal** [comment]
That fixed it! I confirmed all 4 buttons work with or without custom setpoints, and the `customSetpoints: false` is working correctly as well. 

Regarding the transition points being halfway between the setpoints, does it matter if the setpoints for each button are descending or ascending? For example, 100, 50, 12. 0 vs. 0, 12, 50, 100

**Comment by ktownsend-personal** [comment]
I did an experiment on reversing the order of the setpoints. The buttons operate the blinds as expected, but the highlighted button doesn't change (first button stays highlighted). Is it possible to change the midpoint math to handle it? I have 2 main sets of blinds, but to keep the button order consistent I need one set to reverse the setpoint sequence. For example, I'm using labels CLN/OPN/PRT/CLS (clean/open/partial/closed), but the setpoints are different for each set of blinds. One set uses 100/50/12/0 (which works) and the other set uses 0/50/80/100 (not highlighting correctly). 

```yaml
  - entity: cover.master_bath_blinds
    type: 'custom:cover-position-preset-row'
    name: Bath Blinds
    customSetpoints: true
    OpenPosition: 100
    MidOpenPosition: 50
    MidClosePosition: 12
    ClosePosition: 0
    customText: true
    customOpenText: CLN
    customMidOpenText: OPN
    customMidClosedText: PRT
    customClosedText: CLS

  - entity: cover.pool_view_blinds
    type: 'custom:cover-position-preset-row'
    customSetpoints: true
    OpenPosition: 0
    MidOpenPosition: 50
    MidClosePosition: 80
    ClosePosition: 100
    customText: true
    customOpenText: CLN
    customMidOpenText: OPN
    customMidClosedText: PRT
    customClosedText: CLS
```

**Comment by finity69x2** [comment]
Well...I'm not sure. I don't think it should because all I do to find the transition point is add the two adjoining setpoints and then divide by 2 to find the middle.

However, that might be a moot point...

I was waiting to hear whether everything worked as is before I let you know that I'm going to be making some modifications to this as well as all of my custom elements.

For some unknown reason I started using inconsistent option naming conventions so I'm going to change those to all start with a lowercase letter. It will also bring it inline with the other HA config options that all start with lowercase.

the other thing I'm going to do is to add an option to reverse the button order. That has been a request on my other custom elements for a while and I just figured out how I can do it using the simpler binary control row.

But now that I think about it it won't matter so much with this (or seeing your last comment just now maybe it will) since the button names are derived from the setpoints as long as custom setpoints are used. But I think I'm going to include it anyway just for consistency.

Once I get it changed I'll report back here. But in the meantime you can continue to keep using this as it is.

Thanks so much for the help in testing.

**Comment by ktownsend-personal** [comment]
Regarding design, might it be easier to have the buttons defined as an array of button objects? That might make the yaml easier.  It would also make it possible to have a different number of buttons. If array not given you can use default 4 buttons. A button array would make it easier to extend additional settings, such as a selected range rather than trying to infer the range from adjacent buttons. The range can still be inferred if range not given, but there are math challenges there if the buttons are not in an expected order.

For example:
```yaml
- type: 'custom:cover-position-preset-row'
  entity: cover.master_bath_blinds
  name: Blinds Example
  selected_color: orange      # optional global setting for all buttons in the row
  unselected_color: gray      # optional global setting for all buttons in the row
  buttons:                    # optional setting; use default 4 buttons if not given
    - position: 100           # required position if specifying a custom button list
      name: CLN               # optional name override
      selected_color: blue    # optional override of selected color just for this button
      unselected_color: white # optional override of unselected color just for this button
      selected_range:         # optional range for highlight; fallback on inferring with math or exact match on position
        start: 100            # handle these in either order: high to low or low to high
        stop: 85
    - position: 50
      name: OPN
      selected_range:
        start: 86
        stop: 25
    - position: 12
      name: PRT
      selected_range:
        start: 24
        stop: 10
    - position: 0
      name: CLS
      selected_range:
        start: 9
        stop: 0
```
