### ISSUE TITLE
feature request: allow both ascending and descending positions in button order

### ISSUE THREAD

**Issue by ktownsend-personal** [finity69x2/cover-position-preset-row#2]
NOTE: to solve my particular scenario I am going to try your new reverse config setting, but this proposed improvement to the math may still be useful.

Before you implemented the reverse config setting I noticed that when I tried putting my buttons in reverse order (positions 0/50/80/100 instead of 100/80/50/0) the selected button highlight stops working and just the first button stays selected. The actions work as expected, just the highlight doesn't work. We talked before about how your logic calculates the midpoint between buttons to determine the active range for highlighting. I've been thinking about how your midpoint math works and it may just be a matter of using Math.min(...) and Math.max(...) in the comparison. 

I haven't looked at your actual code, but an unproven example of what I mean:
```js
// or'ing the setpoint is to handle the first and last button cases where there is
//   only one adjacent button, so the setpoint is the other bound of the range.

var highlighted = current >= Math.min(midpoint_left|setpoint, midpoint_right|setpoint) 
               && current <= Math.max(midpoint_left|setpoint, midpoint_right|setpoint)
```

An example from my specific scenario:
I have 2 main sets of blinds, but to keep the button order consistent I need one set to reverse the setpoint sequence. For example, I'm using labels CLN/OPN/PRT/CLS (clean/open/partial/closed), but the setpoints are different for each set of blinds. One set uses 100/50/12/0 (which works) and the other set uses 0/50/80/100 (not highlighting correctly). 

```yaml
  - entity: cover.master_bath_blinds
    type: 'custom:cover-position-preset-row'
    name: Bath Blinds
    customSetpoints: true
    OpenPosition: 100
    MidOpenPosition: 50
    MidClosePosition: 12
    ClosePosition: 0
    customText: true
    customOpenText: CLN
    customMidOpenText: OPN
    customMidClosedText: PRT
    customClosedText: CLS

  - entity: cover.pool_view_blinds
    type: 'custom:cover-position-preset-row'
    customSetpoints: true
    OpenPosition: 0
    MidOpenPosition: 50
    MidClosePosition: 80
    ClosePosition: 100
    customText: true
    customOpenText: CLN
    customMidOpenText: OPN
    customMidClosedText: PRT
    customClosedText: CLS
```
