### ISSUE TITLE
feature request: a button array may make config more flexible

### ISSUE THREAD

**Issue by ktownsend-personal** [finity69x2/cover-position-preset-row#3]
Might it be possible to have the buttons defined as an array of button objects? That might make the yaml easier, and also make it possible to have a different number of buttons. If array not given you can use default 4 buttons. A button array would make it easier to extend additional settings, such as a selected range rather than trying to infer the range from adjacent buttons. The range can still be inferred if range not given, but there are math challenges there if the buttons are not in an expected order. It's possible for someone to want their buttons to be in an order that is not ascending or descending, such as 50/12/100/0. In that case, specifying a range in the config would be useful.

For example:
```yaml
- type: 'custom:cover-position-preset-row'
  entity: cover.master_bath_blinds
  name: Blinds Example
  selected_color: orange      # optional global setting for all buttons in the row
  unselected_color: gray      # optional global setting for all buttons in the row
  buttons:                    # optional setting; use default 4 buttons if not given
    - position: 100           # required position if specifying a custom button list
      name: CLN               # optional name override
      selected_color: blue    # optional override of selected color just for this button
      unselected_color: white # optional override of unselected color just for this button
      selected_range:         # optional range for highlight; fallback on inferring with math or exact match on position
        start: 100            # handle these in either order: high to low or low to high
        stop: 85
    - position: 50
      name: OPN
      selected_range:
        start: 86
        stop: 25
    - position: 12
      name: PRT
      selected_range:
        start: 24
        stop: 10
    - position: 0
      name: CLS
      selected_range:
        start: 9
        stop: 0
```
