### ISSUE TITLE
Request - Button Text color

### ISSUE THREAD

**Issue by Pirol62** [finity69x2/cover-position-preset-row#4]
Great work. Perfect for mobiles. Thank you.

Please make the txt color adjustable:
![image](https://user-images.githubusercontent.com/48820003/90367097-963ca980-e068-11ea-8cc3-77655613204b.png)
In certain themes the button text is not readable.

**Comment by finity69x2** [comment]
it just uses the text color from whatever theme you have set.

can you adjust the text in your theme to make it more readable?

**Comment by Pirol62** [comment]
Ah, ok. I have a custom theme. The text color is aligned with the rest.
Ok, then I choose another button color.
Thanks.

**Comment by Pirol62** [comment]
Hmm...I'm confused now.
Following config:
````
entities:
  - closePosition: 0
    midClosePosition: 50
    midOpenPosition: 75
    openPosition: 100
    customClosedText: zu
    customOpenText: offen
    customSetpoints: true
    customText: true
    customTheme: true
    isOpenColor: '#fce4b6'
    isMidOpenColor: '#fce4b6'
    isMidClosedColor: '#fce4b6'
    isClosedColor: '#fce4b6'
    entity: cover.rolladen_wohnzimmer
    name: Wohnzimmer
    reverseButtons: true
    type: 'custom:cover-position-preset-row'
  - closePosition: 0
    customClosedText: zu
    customOpenText: offen
    customSetpoints: true
    customText: true
    customTheme: false
    entity: cover.rolladen_kuche
    midClosePosition: 50
    midOpenPosition: 75
    name: Küche
    openPosition: 100
    reverseButtons: true
    type: 'custom:cover-position-preset-row'
state_color: true
title: Rolläden
type: entities
````
lead to this picture
![image](https://user-images.githubusercontent.com/48820003/90625237-8b754680-e219-11ea-95e2-38c32831be54.png)

Why is the buttons red and not light orange or why is the default grey?
The button is colored, when the status is met to the customized value - good.
The default color should be transparent from my point of view in order to meet a custom theme better.
And the color value might be not accurate calculated.

By the way: this is how my theme look like:
![image](https://user-images.githubusercontent.com/48820003/90627609-751cba00-e21c-11ea-95fa-314e100ae83b.png)
