### ISSUE TITLE
Custom Text does not show correct value

### ISSUE THREAD

**Issue by kayloehmann** [finity69x2/cover-position-preset-row#7]
Hi there, thanks for the plugin.
I have tried to configure the following:

```
type: grid
columns: 1
square: false
title: Rolläden Obergeschoss
cards:
  - type: 'custom:cover-position-preset-row'
    entity: cover.ankleide
    customTheme: true
    isOpenColor: '#009900'
    isMidOpenColor: '#009900'
    isMidClosedColor: '#009900'
    isClosedColor: '#009900'
    buttonInactiveColor: '#666666'
    customSetpoints: true
    openPosition: 100
    midOpenPosition: 75
    midClosePosition: 40
    closePosition: 0
    customText: true
    customOpenText: offen
    customMidOpenText: 75%
    customMidCloseText: 40%
    customClosedText: zu
  - type: 'custom:cover-position-preset-row'
    entity: cover.bad_nord
    customTheme: true
    isOpenColor: '#009900'
    isMidOpenColor: '#009900'
    isMidClosedColor: '#009900'
    isClosedColor: '#009900'
    buttonInactiveColor: '#666666'
    customSetpoints: true
    openPosition: 100
    midOpenPosition: 75
    midClosePosition: 40
    closePosition: 0
    customText: true
    customOpenText: offen
    customMidOpenText: 75%
    customMidCloseText: 40%
    customClosedText: zu
```

However, the ui does show the default values:

<img width="540" alt="grafik" src="https://user-images.githubusercontent.com/34281638/100011556-2f9afa80-2dd2-11eb-8932-18e71a623b6a.png">

Can you please check?

Thanks. Kay.
